export interface LangKeysContract {
  application_name: string
  confirm_password: string
  new_password: string
  app_password: string
  ldap_password: string
  username: string
  password: string
  localization: string
  local_key: string
  arabic_local: string
  english_local: string
  save: string
  login_to_your_account: string
  login: string
  title: string
  change_language: string
  logout: string
  logout_message: string
  users: string
  arabic_name: string
  english_name: string
  email: string
  login_name: string
  status: string
  domain: string
  employee_number: string
  no_records_to_display: string
  actions: string
  edit_permissions: string
  change_password: string
  change: string
  close: string
  password_not_match: string
  password_changed_successfully: string
  permission_change_successfully: string
  permissions: string
  file_size: string
  taskName: string
  description: string
  taskDate: string
  exception: string
  result: string
  tasks: string
  all_tasks: string
  success_tasks: string
  fail_tasks: string
  tasks_filter: string
  clear: string
}
